[config]
name = "yamatt"
count = 20
max_concurrent_requests = 4

[communities]
list = [
    { name = "technology@lemmy.world", weight = -0.5 },
    { name = "cybersecurity@lemmy.world", weight = 0 },
    { name = "futurology@lemmy.world", weight = 0 },
    { name = "todayilearned@lemmy.world", weight = 0 },
    { name = "games@lemmy.world", weight = 0 },
    { name = "nottheonion@lemmy.world", weight = 0 },
    { name = "selfhosted@lemmy.world", weight = 0 },
    { name = "til@lemmy.world", weight = 0 },
    { name = "showerthoughts@lemmy.world", weight = 0 },
    { name = "linux_gaming@lemmy.world", weight = 0 },
    { name = "pics@lemmy.world", weight = 0 },
    { name = "tenforward@lemmy.world", weight = 0 },
    { name = "videos@lemmy.world", weight = 0 },
    { name = "mildlyinteresting@lemmy.world", weight = 0 },
    { name = "gaming@lemmy.world", weight = 0 },
    { name = "politicalhumor@lemmy.world", weight = 0 },
    { name = "science@lemmy.world", weight = 0 },
    { name = "funny@lemmy.world", weight = 0 },
    { name = "xkcd@lemmy.world", weight = 0 },
    { name = "humor@lemmy.world", weight = 0 },
    { name = "upliftingnews@lemmy.world", weight = 0 },
    { name = "interesting@lemmy.world", weight = 0 },
    { name = "london@feddit.uk", weight = 0 },
    { name = "unitedkingdom@feddit.uk", weight = 0 },
    { name = "memes@lemmy.world", weight = 0 },
    { name = "cat@lemmy.world", weight = 0 },
    { name = "cybersecurity@infosec.pub", weight = 0 },
    { name = "bitcoin@infosec.pub", weight = 0 },
    { name = "infosec_news@infosec.pub", weight = 0 },
    { name = "risa@startrek.website", weight = 0 },
    { name = "daystrominstitute@startrek.website", weight = 0 },
    { name = "programmer_humor@programming.dev", weight = 0 },
    { name = "linux@programming.dev", weight = 0 },
    { name = "privacy@programming.dev", weight = 0 },
    { name = "opensource@programming.dev", weight = 0 },
    { name = "programming@programming.dev", weight = 0 },
    { name = "tech@programming.dev", weight = 0 },
    { name = "hardware@programming.dev", weight = 0 },
    { name = "steam@programming.dev", weight = 0 },
    { name = "python@programming.dev", weight = 0 },
    { name = "Aii@programming.dev", weight = 0 },
    { name = "Technology@programming.dev", weight = 0 },
    { name = "security@programming.dev", weight = 0 },
    { name = "commandline@programming.dev", weight = 0 },
    { name = "matrix@programming.dev", weight = 0 },
    { name = "devops@programming.dev", weight = 0 },
    { name = "github@programming.dev", weight = 0 },
    { name = "ublockorigin@programming.dev", weight = 0 },
    { name = "technology@lemmy.today", weight = 0 },
    { name = "science@lemmy.today", weight = 0 },
    { name = "general@retrolemmy.com", weight = 0 },
    { name = "science_memes@mander.xyz", weight = 0 },
    { name = "science@mander.xyz", weight = 0 },
    { name = "dataisbeautiful@mander.xyz", weight = 0 },
]
