[config]
name = "yamatt"
count = 20

[communities]
list = [
    "technology@lemmy.world",
    "cybersecurity@lemmy.world",
    "futurology@lemmy.world",
    "todayilearned@lemmy.world",
    "interesting@lemmy.world",
    "london@feddit.uk",
    "unitedkingdom@feddit.uk",
    "memes@lemmy.world ",
    "cats@lemmy.world",
    "cybersecurity@infosec.pub",
    "bitcoin@infosec.pub",
    "infosec_news@infosec.pub",
    "risa@startrek.website",
    "daystrominstitute@startrek.website",
    "programmer_humor@programming.dev",
    "linux@programming.dev",
    "privacy@programming.dev",
    "opensource@programming.dev",
    "programming@programming.dev",
    "tech@programming.dev",
    "hardware@programming.dev",
    "steam@programming.dev",
    "python@programming.dev",
    "Aii@programming.dev",
    "Technology@programming.dev",
    "security@programming.dev",
    "commandline@programming.dev",
    "matrix@programming.dev",
    "devops@programming.dev",
    "github@programming.dev",
    "ublockorigin@programming.dev",
    "technology@lemmy.today",
    "science@lemmy.today",
    "general@retrolemmy.com",
    "science_memes@mander.xyz",
    "science@mander.xyz",
    "dataisbeautiful@mander.xyz",

]
