[config]
name = "yamatt"
count = 20

[communities]
list = [
    "technology@lemmy.world",
    "cybersecurity@lemmy.world",
    "futurology@lemmy.world",
    "todayilearned@lemmy.world",
    "interesting@lemmy.world",
]
