name: Build RSS

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/rss.yaml"
      - "ddor/**"
      - "config/*"

concurrency:
  group: "{{ github.workflow }}-rss"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-rss:
    name: Build RSS feed
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync
      - name: Create RSS
        timeout-minutes: 5
        run: |
          mkdir public
          uv run -m ddor config/yamatt.toml public
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
